[workspace]
members = [
    "arithmetic-and-type-casting",
    "console-input",
    "dataTypes",
    "flow-control",
    "functions",
    "HelloWorld",
    "ownership",
    "Struct",
    "variables"
]
